title: Coping with COVID
description: [Coping with COVID](https://copingwithpandemic.xyz/#/)
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: 'https://github.com/coping-with-covid/coping-with-covid'
