title: Coping with COVID
description: <a href="https://copingwithpandemic.xyz/#/">Coping with COVID</a>
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: 'https://github.com/coping-with-covid/coping-with-covid'
